In [2]:
import numpy as np
# 과제
ar2 = np.arange(1,10).reshape(3,3)
ar2


# Q. ar2에서 슬라이싱을 사용해서 아래와 같이 출력하세요 
# [[1 2]
#  [4 5]]

# (2가지 방법)
# [[4 5 6]
# [7 8 9]]

# [[1 2 3]
# [4 5 6]
# [7 8 9]]

# [[2 3]
# [5 6]]

# [1 4]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# 1
ar2[:2,:2]  # 행// 열

array([[1, 2],
       [4, 5]])

In [4]:
# 2-1
ar2[1:3,:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [5]:
#2-2
np.array(ar2)[1:3]

# print(ar2[1:,:])


array([[4, 5, 6],
       [7, 8, 9]])

In [6]:
#2-3
ar2[np.array([1,2])]

array([[4, 5, 6],
       [7, 8, 9]])

In [7]:
#3-1
ar2[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#3-2
np.array(ar2)[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#3-3
ar2[np.array([0,1,2])]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#4-1
ar2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
#5 # [1 4]
ar2[:2,:1]

array([[1],
       [4]])

In [12]:
ar2[:2,0]

array([1, 4])