In [257]:
# 파이썬 random함수 

import random

print(random.random()) #0과 1 사이의 실수 뽑아줌

print (random.randint(1,10)) #0~10 사이의 정수

print(random.uniform(10,20)) # 실수 뽑아줌

print(random.randrange(10))  # 0~9 지정범위에서 int값 

print(random.choice([1,2,3,4,5])) # 랜덤으로 뽑아주기

li= [1,2,3,4,5]
print(random.sample(li,3))  # 리스트 요소를 중복없이 뽑아주는것.. 

random.shuffle(li)   # 랜덤으로 섞어주기
print(li)

0.4957165797921629
6
11.037235124044267
9
4
[4, 5, 3]
[3, 4, 1, 5, 2]


In [260]:
# 넘파이의 np.random
# rand : 0.0~1.0 사이의 균일 분포 (실수)
# randn : 가우시안 표준 정규 분포
# randint : 균일 분포의 정수 난수


In [268]:
# rand : 0.0~1.0 사이의 균일 분포 (실수)

import numpy as np

np.random.seed(0)

np.random.rand(5) #실수 5개 랜덤!

np.random.rand(3,2) #3행 2열 실수 랜덤! 

array([[0.64589411, 0.43758721],
       [0.891773  , 0.96366276],
       [0.38344152, 0.79172504]])

In [267]:
# randint - 0~4까지 에서 정수 난수
np.random.randint(5)
np.random.randint(1,20)
np.random.randint(10,size=10) # 중복 가능 


array([2, 0, 3, 5, 9, 4, 4, 6, 4, 4])

In [266]:
# array도 만들 수 있엉 
np.random.randint(10,20,size=(3,5)) 

array([[15, 15, 16, 18, 14],
       [11, 14, 19, 18, 11],
       [11, 17, 19, 19, 13]])

In [272]:
np.random.choice([1,2,3,4,5])
np.random.choice(5,5, replace=False)  # 중복 안됨 (비복원추출)
np.random.choice(5,5) # 중복 됨 ! (복원추출)

array([0, 1, 1, 1, 0])

In [274]:
list= [0,1,2,3,4]
np.random.shuffle(list)
# np.random.choice(5,5, replace=False) 
list

[1, 4, 0, 3, 2]

In [276]:
np.random.randn(6) # 표준정규분포에서 난수 n개 뽑아주기 
np.random.randn(3,2) # 3행2열로 뽑아주기

array([[ 0.61495732,  1.42966077],
       [-0.21195226, -0.08033726],
       [ 0.40539778,  0.11860659]])

In [281]:
# 범위 내 n개 실수 출력
np.random.uniform(1.0,2.0,3) # 1.0~2.0 중 3개 실수 뽑아줌
np.random.uniform(0,1,(2,3))

array([[0.91823547, 0.21682214, 0.56518887],
       [0.86510256, 0.50896896, 0.91672295]])

In [278]:
# 0~1사이의 실수 n개 또는 행렬로 뽑아주기 
# random_sample은 uniform 하수의 최소,최대값을 각각0,1로 
#지정한 것과 같음 
np.random.random_sample((2,3)) 
# np.random.uniform(0,1,(2,3))

array([[0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232]])