In [1]:
# 레이블 인코딩 
from sklearn.preprocessing import LabelEncoder

items= ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
labels= encoder.fit_transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [2]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [3]:
print('디코딩 원본 값:',encoder.inverse_transform([0,1,4,5,3,3,2,2]))


디코딩 원본 값: ['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


In [4]:
# 원-핫 인코딩  
# 숫자의 크기를 해결할 수 있음. but 컬럼이 부풀려짐 (변수가 많아짐), 정확도가 높아짐 (분류모델,회귀모델의 경우)
# 회귀에서는 규제를 가하는 것을 적용 (l2 적용: 릿지모델 //  l1 적용:랏지모델)
# --> 규제로 부작용 보정함 

# 레이블 인코딩 먼저 해줌
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items= ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder= LabelEncoder()
labels= encoder.fit_transform(items)
labels= labels.reshape(-1,1)
labels

oh_encoder= OneHotEncoder()
oh_labels= oh_encoder.fit_transform(labels)
print('원-핫 인코딩:')
print(oh_labels.toarray())

원-핫 인코딩:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [5]:
# 과제 
# Q. items를 pd.get_dummies()를 사용하여 원핫 인코딩 하세요 
# items= ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
import pandas as pd

items_oh= pd.get_dummies(items)
items_oh

TV  냉장고  믹서  선풍기  전자레인지  컴퓨터
0   1    0   0    0      0    0
1   0    1   0    0      0    0
2   0    0   0    0      1    0
3   0    0   0    0      0    1
4   0    0   0    1      0    0
5   0    0   0    1      0    0
6   0    0   1    0      0    0
7   0    0   1    0      0    0

In [6]:
# 과제
# 붓꼿 데이터 셋의 독립변수들을 2가지 방법으로 스케일링 한 후
# 평균값과 분산 값을 출력하세요.
# - 0과 1사이의 분포로 스케일링 
# - 평균 0 , 표준편차 1인 분포로 스케일링 

In [7]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split


In [19]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [25]:
iris_df= pd.DataFrame(data= iris.data , columns=iris.feature_names)
iris_df.head()

print('mean:\n',iris_df.mean())
print()
print('std:\n',iris_df.std())

mean:
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

std:
 sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64


In [30]:
# 정규화
from sklearn.preprocessing import MinMaxScaler

scaler_MM= MinMaxScaler()
iris_scale_MM = scaler_MM.fit_transform(iris_df)
iris_scale_MM_df = pd.DataFrame(iris_scale_MM, columns=iris_df.columns)
iris_scale_MM_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
..                 ...               ...                ...               ...
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]

In [31]:
print('mean:\n',iris_scale_MM_df.mean())
print()
print('std:\n',iris_scale_MM_df.std())

mean:
 sepal length (cm)    0.428704
sepal width (cm)     0.440556
petal length (cm)    0.467458
petal width (cm)     0.458056
dtype: float64

std:
 sepal length (cm)    0.230018
sepal width (cm)     0.181611
petal length (cm)    0.299203
petal width (cm)     0.317599
dtype: float64


In [33]:
# 표준화 
from sklearn.preprocessing import StandardScaler

scaler_SS = StandardScaler()
iris_scale_SS = scaler_SS.fit_transform(iris_df)
iris_scale_SS_df = pd.DataFrame(iris_scale_SS, columns=iris_df.columns)
iris_scale_SS_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [34]:
print('mean:\n',iris_scale_SS_df.mean())
print()
print('std:\n',iris_scale_SS_df.std())

mean:
 sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

std:
 sepal length (cm)    1.00335
sepal width (cm)     1.00335
petal length (cm)    1.00335
petal width (cm)     1.00335
dtype: float64
