In [3]:
import statsmodels.api as sm

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('seaborn-dark')
%config InlineBackend.figure_format = 'retina'
pd.options.display.max_rows = 20
pd.options.display.max_columns = 20

plt.rcParams["figure.figsize"] = (14,4)
plt.rcParams['lines.linewidth'] = 2
plt.rcParams['lines.color'] = 'r'
plt.rcParams['axes.grid'] = True 

## 빅데이터 기반 AI 응용 솔루션 개발자 전문과정

### 교과목명 : 통계 및 ml 기초
- 평가일 : 21.8.20
- 성명 : 채승혜
- 점수 : 65점

Q1. 다음 괄호안에 들어갈 적합한 단어를 기술하세요.(20점)

확률 변수(random variable)은 확률 실험의 결과에 대한 숫자적 표현입니다. 가령 동전을 던진다고 했을 때 앞면을 1, 뒷면을 0이라고 표현한다고 하면 이는 실험 결과의 숫자적 표현이고 확률 변수입니다. 확률 변수는 그것이 취할 수 있는 값들이 한 개, 두개와 같이 셀 수 있으면 ( 이산 ) 확률 변수(discrete random variable), 셀 수 없을 경우 ( 연속 ) 확률 변수(continuous random variable)이라 부릅니다. 동전의 경우 나올 수 있는 경우의 수가 앞 면 또는 뒷 면으로 두 가지니까니 ( 이산 ) 확률 변수입니다. 그러나 같은 반 아이들의 키 처럼 확률 변수가 가질 수 있는 가지 수가 무한한 경우 (  연속 ) 확률 변수에 속하게 됩니다.

확률변수가 취할 수 있는 값들에는 확률이 대응되어 있고, 이를 (  확률분포  )라고 합니다. 즉 확률 변수들이 어떠한 형태로 놓여있을까, 어떻게 분포해 있을까를 나타내주는 함수입니다. (  확률분포  ) 역시 확률 변수가 이산형 확률 변수이냐, 연속형 확률 변수이냐에 따라서 (  이산확률분포  ), (  연속확률분포   )로 나뉩니다.

(  포아송분포  )란 고정된 지역, 시간 또는 부피 등에서 관심 있는 사건의 관찰 수 또는 발생 횟수 X를 표현하는데 사용되는 분포입니다. 예를 들면 하루 동안 서버에 접속한 사용자 수, 어느 주말 일요일에 발생한 교통사고 사망자 수 등이 있습니다. 

평균을 중심으로 좌우가 대칭인 종 모양을 그리는 ( 정규분포 )는 표준 편차가 높을 수록 그래프는 완만한 곡선 형태를 띄게 됩니다. 

현실 세계의 많은 데이터들은 정규분포를 따르고 있습니다. 하지만 각 집단의 평균과 표준 편차가 모두 다르기 때문에 데이터들을 서로 비교하기가 어렵습니다. 예를 들어 A반의 수학 점수가 평균은 70점이고 표준 편자는 30점입니다. 반면 B반은 평균 65점에 표준 편차가 10점이라면 두 반 중 어느 반이 더 수학  점수가 높다고 할 수 있을까요? 이러한 비교를 위해서 전체 데이터를 평균으로 빼주고, 표준 편차로 나누어 주는 표준화(standardizing) 작업을 거치게 됩니다. 그 결과 두 집단의 수학 점수는 동일하게 (   z-분포  )를 따르게 되며 평균이 0이고 분산이 1인 정규 분포가 됩니다. 수식으로는 Z = (X - mu) / sigma로  표현할 수 있습니다. 표준화를 거친 개별 데이터를 우리는 (  z-score  )라고 부릅니다.

( t분포 )는 정규 분포인 모집단의 모평균을 표본 평균을 통해서 추측할 때 사용되는 분포입니다. 정규 분포와 유사한 형태를 갖지만 양 끝단에 데이터가 더 많이 분포하는 형태를 띕니다. 모집단에서 표본을 추출할 경우 표준 편차가 더 커질 것이라는 것을 예상할 수 있습니다. 이 때문에 곡선의 모양이 더 완만해 지는 것을 ( t분포 )로 설명한다고 이해하면 좋을 것 같습니다.

정규 분포의 경우 그래프의 형태를 표준 편차와 평균이 결정하였습니다. t-분포는 이 둘에 더해 수식 상에서 (n-1)에 해당하는 ( 자유도 )가 그래프의 형태에 영향을 줍니다. (  자유도 )의 정의는 말 그래도 자유스러운 정도로 특정 분포에서 그래프의 모양을 결정하는 모수입니다. 대표적으로 t 분포와 카이제곱 분포가 (  자유도  )를 모수로 갖습니다.

(  f-분포  )는 f 검정이나 분산 분석에서 많이 활용된다고 합니다. ( f-분포  )는 두 모분산의 비율에 대한 추정을 할 떄 사용됩니다.

(  카이제곱검정   )관찰된 빈도가 기대 빈도와 통계적으로 다른지를 판단하는 검증방법으로 사용한다.

모집단의 표본에서 얻은 통계량을 통해
모집단의 통계적 특성을 추측할 수 있습니다. 이러한 과정을 논리적으로 전개하기 위해서 필요한 것이 가설과 검정입니다. 가설(hypothesis)란 확률 분포에 대한 어떠한 주장이며 이를 증명하는 행위를 검정(testing)이라 합니다. 특히 확률 분포의 모수 값에 대한 가설을 검정하는 것을 ( 모수검정 )이라 부릅니다.

( 귀무가설 )은 처음부터 버릴 것을 예상하는 가설입니다. 기본적으로 참으로 추정되며 이를 거부하기 위해서는 증거가 반드시 필요합니다. 예를들어 형사가 용의자를 잡았을 경우에도 무죄 추정의 원칙에 따라서 '이 용의자는 무죄일 것이다' 라는 가설을 먼저 세우게 됩니다.(  15  )을 세울 때에는 특별한 증거가 없다면 참으로 여겨지는 가설을 (  귀무가설  )로 세우게 됩니다.

( 1종 오류  )란 귀무 가설이 맞는데도 이를 잘못 기각하여 발생하는 오류입니다.  용의자가 무죄가 맞지만 잘못하여 유죄 판결을 내리는 것과 같습니다. (  2종 오류  )란 대립 가설이 사실임에도 불구하고 귀무가설을 기각하지 못하는 오류를 말합니다. 용의자가 범인이 맞지만 무죄가 아니라는 것을 입증해내지 못하는 것을 말합니다.

(  p-value p값  )란 귀무 가설이 맞다고 가정할 때 얻은 결과보다 극단적인 결과가 관측될 확률입니다.

(  유의수준  )은 귀무가설을 기각하는 기준이 되는 값이다.

통계모델에 사용하는 파라미터를 계수라고 하는 반면 머신러닝에서는 (  가중치**  )라고 표현한다.

Q2. 다음의 확률밀도함수를 그래프로 표현하고 모집단 분포와 비교한 후 t분포의 특징을 기술하세요.(5)
- 표준정규분포
- 표준정규분포인 모집단에서 샘플 10개를 추출한 표본의 t분포
- 평균 0, 표준편차 2인 정규분포
- 평균 0, 표준편차 2인 정규분포인 모집단에서 샘플 5개를 추출한 표본의 t분포

In [4]:
# from scipy import stats

# stats.norm.pdf(x=x)
# # plt.plot(x,stats.norm.pdf(x=x))

In [5]:
# from scipy import stats
# xx = stats.norm(loc=0,scale=2)
# plt.plot(xx,stats.norm.pdf(x=x))

In [11]:
plt.plot(x_plot,stats.norm.pdf(x=x_plot,loc=4,scale=0.8),color='k')

NameError: name 'x_plot' is not defined

In [12]:
from scipy import stats
xx = stats.norm(loc=0,scale=2)
xx.rvs(size=10)

array([ 0.28808714,  2.90854701,  1.52207545,  0.24335003,  0.88772647,
        0.66734865,  2.98815815, -0.41031653,  0.6261354 , -1.70819148])

Q3. t검정과 관련 다음 사항에 대하여 기술하세요.(5)
- t검정을 사용하는 경우
- t검정에 사용하는 t-value 산출 방법 
- t-value와 z score 간의 의미상 차이

In [13]:
1. 그룹이 2개 이하일 때 t검정을 사용한다
2. t_value = (표본평균 - 모평균)/ 표준오차 
:: 샘플사이즈는 커지고 데이터 분산은 적어지고 평균값의 차이는 커질 때 유의미한 차이가 있음
3. 

SyntaxError: invalid syntax (<ipython-input-13-ca01ccbeda4a>, line 1)

Q4. 남성 키의 평균 170 표준편차는 5인 모집단 생성(size=2000) 후 그 중 10개를 출력하세요.

In [14]:
np.random.seed(0)
data= stats.norm(loc=170, scale=5)
data.rvs(size=10)

array([178.82026173, 172.00078604, 174.89368992, 181.204466  ,
       179.33778995, 165.1136106 , 174.75044209, 169.24321396,
       169.48390574, 172.05299251])

Q5. Q4에서 생성된 모집단에서 20개의 샘플을 추출한 후 아래 사항을 수행하세요. 단 모집단의 분산은 알 수가 없다는 것을 가정한다.
- 추출한 샘플1, 샘플2로 부터 남성의 평균 키가 170이다라는 가설을 세우고 검정
- 샘플2를 기준으로 표준오차를 구하세요
- 샘플2를 기준으로 95% 신뢰수준으로 신뢰구간을 구하세요

In [15]:
np.random.seed(0)
sample1= data.rvs(size=20)
sample2= data.rvs(size=20)

print(sample1)
print()
print(sample2)

[178.82026173 172.00078604 174.89368992 181.204466   179.33778995
 165.1136106  174.75044209 169.24321396 169.48390574 172.05299251
 170.72021786 177.27136753 173.80518863 170.60837508 172.21931616
 171.66837164 177.47039537 168.97420868 171.56533851 165.7295213 ]

[157.23505092 173.26809298 174.32218099 166.2891749  181.34877312
 162.72817163 170.22879259 169.06408075 177.66389607 177.34679385
 170.77473713 171.8908126  165.56107126 160.09601766 168.26043925
 170.78174485 176.1514534  176.01189924 168.06336591 168.48848625]


In [16]:
stats.ttest_1samp(sample1,170)

Ttest_1sampResult(statistic=2.918986310409787, pvalue=0.008803359459852944)

In [17]:
stats.ttest_1samp(sample2,170)

Ttest_1sampResult(statistic=0.20458488702989824, pvalue=0.840072088821795)

In [8]:
sample2_std= np.std(sample2,ddof=1) 
sample2_se= sample2_std/np.sqrt(len(sample2))
sample2_se

1.3625237498252973

In [9]:
# 신뢰구간 
mu= np.mean(sample2)
sigma= np.std(sample2,ddof=1)
se= sigma/np.sqrt(len(sample2))
df= len(sample2)-1

interval= stats.t.interval(alpha=0.95 ,df=df, loc=mu,scale=se) # alpha: 신뢰수준
interval

(167.42695678434666, 173.13054675052047)

In [10]:
# sample 추출
# import random
# import numpy as np 
# np.random.seed(0)
# sample1 = np.random.choice(data,20,replace=False)
# sample2 = data[:20]
# sample1

In [11]:
# print(sample1.mean())
# print(sample2.mean())

Q6. 어느 자동차 임대 회사에서 3가지 종류의 휘발유를 비교하는데 관심이 있다. 각 종류의 휘발유에 대하여 4번의 주행을 하여 반응변수로서 각 주행에 대한 리터당 주행거리를 구하였다.(qsample.csv) 다음 사항을 고려하여 휘발유간의 주행거리 차이가 유의미한지를 분산분석을 사용하여 검정하세요.
- 각 휘발유의 4개의 실험에서의 주행거리가 다름 = 실험오차(군내변동)
- 휘발유 종류에 따라 각 평균 주행거리가 서로 다름(군간변동)

In [12]:
import pandas as pd
df = pd.read_csv('dataset/qsample.csv')
df.head(1)

product  distance
0     제품1      15.2

In [13]:
df.groupby('product').mean()

distance
product          
제품1          16.0
제품2          18.0
제품3          19.0

In [28]:
# 군내 변동
dict = df.groupby('product')['distance'].mean().to_dict()

qq = df['product'].apply(lambda x : dict[x])
qq

0     16.0
1     16.0
2     16.0
3     16.0
4     18.0
5     18.0
6     18.0
7     18.0
8     19.0
9     19.0
10    19.0
11    19.0
Name: product, dtype: float64

In [ ]:
# 군간 변동
ww = np.sum((df.distance - df.distance.mean())**2).round(3)
ww

Q7. 비만과 당뇨의 상관관계를 분석하기 위하여 조사한 결과로 qsample2 데이터를 작성하였다. 비만과 당뇨가 서로 독립적인지를 판단하기 위한 카이스퀘어 검정을 수행 하세요.

In [18]:
obs = pd.read_csv('dataset/qsample2.csv',index_col = 'index')
obs

당뇨  정상
index        
비만체중   10  10
정상체중   15  65

In [19]:
stats.chi2_contingency(obs, correction=False)

(8.333333333333334,
 0.003892417122778637,
 1,
 array([[ 5., 15.],
        [20., 60.]]))

Q8.'7_1_beer.csv' 데이터 셋에서 온도의 변화에 따른 맥주 매상 예측 모델을 statsmodel 라이브러리를 활용하여 수행 후 summary() 결과를 해석하세요. 

In [17]:
beer = pd.read_csv('dataset/7_1_beer.csv')
beer.head()

beer  temperature
0  45.3         20.5
1  59.3         25.0
2  40.4         10.0
3  38.0         26.9
4  37.0         15.8

In [18]:
import statsmodels.formula.api as smf
import statsmodels.api as sm

lm_model = smf.ols(formula="beer ~ temperature",data=beer).fit()
lm_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   beer   R-squared:                       0.504
Model:                            OLS   Adj. R-squared:                  0.486
Method:                 Least Squares   F-statistic:                     28.45
Date:                Fri, 20 Aug 2021   Prob (F-statistic):           1.11e-05
Time:                        16:17:01   Log-Likelihood:                -102.45
No. Observations:                  30   AIC:                             208.9
Df Residuals:                      28   BIC:                             211.7
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      34.6102      3.235     10.699      0.000      27.984      41.237
temperature     0.7654      0.144      5.334      0.000       0.471       1.059
==============================================================================
Omnibus:                        0.587   Durbin-Watson:                   1.960
Prob(Omnibus):                  0.746   Jarque-Bera (JB):                0.290
Skew:                          -0.240   Prob(JB):                        0.865
Kurtosis:                       2.951   Cond. No.                         52.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

목표변수 :beer 
회귀분석모델 : ols (ordinary least squares) 
파라미터 최적화 방법: Least Squares 
관찰 데이터 쌍 개수 :30개
파라미터 수 :1
잔차의 자유도: 30- 파라미터수(1)-1 = 28

결정계수: 0.4 이상이므로 선형모형이 적합하다 (유의미하다)
Prob (f-statistic) 이 0.05 이하이므로 회귀식은 유의미하다. 



Q9.iris 데이터셋으로 분류 분석을 수행하고 평가하세요. 

In [21]:
from sklearn.datasets import load_iris

In [22]:
iris = load_iris()
iris_label=iris.target
iris_data=iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris_label
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [23]:
from sklearn.model_selection import train_test_split

X = iris_df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)','petal width (cm)']]
y = iris_df['label']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [24]:
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print(f'정확도: {accuracy_score(y_test,pred):.3f}')

정확도: 0.967


Q10. 'auto-mpg' 데이터셋에서 horsepower에 따른 mpg를 예측하는 선형회귀 모델을 생성한 후 정확도 평가를 수행하세요.(단, 종속변수의 정규성을 개선해야 함)

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.linear_model import LinearRegression

In [34]:
df = pd.read_excel("./dataset/auto-mpg.xlsx")
ndf=df[['mpg','cylinders','horsepower','weight']]
ndf.head()

mpg  cylinders horsepower  weight
0  18.0          8        130    3504
1  15.0          8        165    3693
2  18.0          8        150    3436
3  16.0          8        150    3433
4  17.0          8        140    3449

In [35]:
ndf.horsepower = ndf.horsepower.replace('?',np.nan)
ndf.horsepower = ndf.horsepower.fillna(ndf.horsepower.mean())
X = ndf[['cylinders','horsepower','weight']]
y = ndf['mpg']

C:\Tools\Anaconda3\lib\site-packages\pandas\core\generic.py:5494: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [36]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
scaler1 = StandardScaler()
scaler2 = MinMaxScaler()

# sns.distplot()
# scaler1(y)
a = scaler1.fit_transform(pd.DataFrame(y))
b = scaler2.fit_transform(pd.DataFrame(y))
c = np.log1p(y)


In [37]:
# Standard scale
X_train, X_test, y_train, y_test = train_test_split(X,a,
                                                   test_size=0.3,
                                                   random_state=0)

lr = LinearRegression()
lr.fit(X_train, y_train)
y_preds = lr.predict(X_test)

r2 = r2_score(y_test, y_preds)
mse = mean_squared_error(y_test, y_preds)
rmse = np.sqrt(mse)

print ('정확도 : ',r2)
print ('mse : ',mse)
print ('rmse : ',rmse)

정확도 :  0.7013388334963051
mse :  0.3131970173537249
rmse :  0.5596400784019359


In [39]:
# MinMax scale
X_train, X_test, y_train, y_test = train_test_split(X,b,
                                                   test_size=0.3,
                                                   random_state=0)

lr = LinearRegression()
lr.fit(X_train, y_train)
y_preds = lr.predict(X_test)

r2 = r2_score(y_test, y_preds)
mse = mean_squared_error(y_test, y_preds)
rmse = np.sqrt(mse)

print ('정확도 : ',r2)
print ('mse : ',mse)
print ('rmse : ',rmse)

정확도 :  0.7013388334963051
mse :  0.013499470073218061
rmse :  0.11618721992206398
